### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by Cogito2012** [Cysu/dgd_person_reid#1]
When I run  scripts/exp_jstl.sh on my Tesla K80 （12G memory per GPU）,and cudnn v3 , errors happened like this:
///////////////////////////////////////////////////
I0516 02:05:37.825336  5661 solver.cpp:258] Learning Rate Policy: stepdecr
I0516 02:05:37.868683  5661 solver.cpp:316] Iteration 0, Testing net (#0)
I0516 02:05:38.794275  5662 cudnn_conv_layer.cpp:179] Optimized cudnn conv
I0516 02:05:39.005478  5661 cudnn_conv_layer.cpp:179] Optimized cudnn conv
I0516 02:08:07.847208  5662 solver.cpp:373]     Test net output #0: accuracy = 0
I0516 02:08:07.847247  5662 solver.cpp:373]     Test net output #1: loss = 7.87437 (* 1 = 7.87437 loss)
I0516 02:08:09.886698  5662 solver.cpp:221] Iteration 0, loss = 7.87508
I0516 02:08:09.886761  5662 solver.cpp:236]     Train net output #0: loss = 7.87812 (* 1 = 7.87812 loss)
I0516 02:08:09.886782  5662 solver.cpp:542] Iteration 0, lr = 0.1
I0516 02:08:09.908810  5661 solver.cpp:373]     Test net output #0: accuracy = 0
I0516 02:08:09.908860  5661 solver.cpp:373]     Test net output #1: loss = 7.87291 (* 1 = 7.87291 loss)
F0516 02:08:10.520869  5661 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f085e6939fd  google::LogMessage::Fail()
    @     0x7f085e69589d  google::LogMessage::SendToLog()
    @     0x7f085e6935ec  google::LogMessage::Flush()
    @     0x7f085e6961be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f085ed8b98b  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f085edb08c1  caffe::Blob<>::mutable_gpu_data()
    @     0x7f085edddd1b  caffe::BNLayer<>::Forward_gpu()
    @     0x7f085ec70a2c  caffe::Net<>::ForwardFromTo()
    @     0x7f085ec70cbf  caffe::Net<>::ForwardPrefilled()
    @     0x7f085eda6813  caffe::Solver<>::Step()
    @     0x7f085eda730b  caffe::Solver<>::Solve()
    @           0x408b04  train()
    @           0x4067ad  main
    @     0x7f085dbaaec5  (unknown)
    @           0x406bc8  (unknown)
F0516 02:08:10.585333  5662 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f8cbd9429fd  google::LogMessage::Fail()
    @     0x7f8cbd94489d  google::LogMessage::SendToLog()
    @     0x7f8cbd9425ec  google::LogMessage::Flush()
    @     0x7f8cbd9451be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8cbe03a98b  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f8cbe05f8c1  caffe::Blob<>::mutable_gpu_data()
    @     0x7f8cbe04c4dd  caffe::SGDSolver<>::ComputeUpdateValue()
    @     0x7f8cbe049b53  caffe::SGDSolver<>::ApplyUpdate()
    @     0x7f8cbe055ed6  caffe::Solver<>::Step()
    @     0x7f8cbe05630b  caffe::Solver<>::Solve()
    @           0x408b04  train()
    @           0x4067ad  main
    @     0x7f8cbce59ec5  (unknown)
    @           0x406bc8  (unknown)
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 5661 on node k-SYS-7048GR-TR exited on signal 6 (Aborted).
--------------------------------------------------------------------------
Extracting train set
E0516 02:08:12.211585  7957 extract_features.cpp:54] Using GPU
E0516 02:08:12.211988  7957 extract_features.cpp:60] Using Device_id=0
F0516 02:08:33.885123  7957 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7f7df020d9fd  google::LogMessage::Fail()
    @     0x7f7df020f89d  google::LogMessage::SendToLog()
    @     0x7f7df020d5ec  google::LogMessage::Flush()
    @     0x7f7df02101be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7df0688f84  caffe::ReadProtoFromBinaryFile()
    @     0x7f7df06a69cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f7df059e47a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f7df059e501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7f7def642ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  7957 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting val set
E0516 02:08:36.303149  8098 extract_features.cpp:54] Using GPU
E0516 02:08:36.303547  8098 extract_features.cpp:60] Using Device_id=0
F0516 02:08:55.747742  8098 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7fb37d22a9fd  google::LogMessage::Fail()
    @     0x7fb37d22c89d  google::LogMessage::SendToLog()
    @     0x7fb37d22a5ec  google::LogMessage::Flush()
    @     0x7fb37d22d1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb37d6a5f84  caffe::ReadProtoFromBinaryFile()
    @     0x7fb37d6c39cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fb37d5bb47a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fb37d5bb501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7fb37c65fec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8098 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_probe set
E0516 02:08:58.312100  8225 extract_features.cpp:54] Using GPU
E0516 02:08:58.312475  8225 extract_features.cpp:60] Using Device_id=0
F0516 02:09:22.046344  8225 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7f90784889fd  google::LogMessage::Fail()
    @     0x7f907848a89d  google::LogMessage::SendToLog()
    @     0x7f90784885ec  google::LogMessage::Flush()
    @     0x7f907848b1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9078903f84  caffe::ReadProtoFromBinaryFile()
    @     0x7f90789219cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f907881947a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f9078819501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7f90778bdec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8225 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_gallery set
E0516 02:09:23.331884  8362 extract_features.cpp:54] Using GPU
E0516 02:09:23.332203  8362 extract_features.cpp:60] Using Device_id=0
F0516 02:09:46.931263  8362 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7fd12e2489fd  google::LogMessage::Fail()
    @     0x7fd12e24a89d  google::LogMessage::SendToLog()
    @     0x7fd12e2485ec  google::LogMessage::Flush()
    @     0x7fd12e24b1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd12e6c3f84  caffe::ReadProtoFromBinaryFile()
    @     0x7fd12e6e19cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fd12e5d947a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fd12e5d9501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7fd12d67dec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8362 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting train set
E0516 02:09:48.710749  8503 extract_features.cpp:54] Using GPU
E0516 02:09:48.717394  8503 extract_features.cpp:60] Using Device_id=0
F0516 02:10:12.159739  8503 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7ffceedaa9fd  google::LogMessage::Fail()
    @     0x7ffceedac89d  google::LogMessage::SendToLog()
    @     0x7ffceedaa5ec  google::LogMessage::Flush()
    @     0x7ffceedad1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ffcef225f84  caffe::ReadProtoFromBinaryFile()
    @     0x7ffcef2439cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7ffcef13b47a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7ffcef13b501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7ffcee1dfec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8503 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting val set
E0516 02:10:14.713034  8647 extract_features.cpp:54] Using GPU
E0516 02:10:14.713467  8647 extract_features.cpp:60] Using Device_id=0
F0516 02:10:37.292449  8647 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7f8d79dc19fd  google::LogMessage::Fail()
    @     0x7f8d79dc389d  google::LogMessage::SendToLog()
    @     0x7f8d79dc15ec  google::LogMessage::Flush()
    @     0x7f8d79dc41be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8d7a23cf84  caffe::ReadProtoFromBinaryFile()
    @     0x7f8d7a25a9cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f8d7a15247a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f8d7a152501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7f8d791f6ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8647 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_probe set
E0516 02:10:39.804507  8794 extract_features.cpp:54] Using GPU
E0516 02:10:39.804853  8794 extract_features.cpp:60] Using Device_id=0
F0516 02:11:02.423830  8794 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7fe71b0db9fd  google::LogMessage::Fail()
    @     0x7fe71b0dd89d  google::LogMessage::SendToLog()
    @     0x7fe71b0db5ec  google::LogMessage::Flush()
    @     0x7fe71b0de1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe71b556f84  caffe::ReadProtoFromBinaryFile()
    @     0x7fe71b5749cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fe71b46c47a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fe71b46c501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7fe71a510ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8794 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_gallery set
E0516 02:11:04.005192  8961 extract_features.cpp:54] Using GPU
E0516 02:11:04.011663  8961 extract_features.cpp:60] Using Device_id=0
F0516 02:11:27.216060  8961 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7fcbfa62d9fd  google::LogMessage::Fail()
    @     0x7fcbfa62f89d  google::LogMessage::SendToLog()
    @     0x7fcbfa62d5ec  google::LogMessage::Flush()
    @     0x7fcbfa6301be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fcbfaaa8f84  caffe::ReadProtoFromBinaryFile()
    @     0x7fcbfaac69cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fcbfa9be47a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fcbfa9be501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7fcbf9a62ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  8961 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting train set
E0516 02:11:29.147552  9129 extract_features.cpp:54] Using GPU
E0516 02:11:29.147971  9129 extract_features.cpp:60] Using Device_id=0
F0516 02:11:49.092274  9129 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7f29d27f19fd  google::LogMessage::Fail()
    @     0x7f29d27f389d  google::LogMessage::SendToLog()
    @     0x7f29d27f15ec  google::LogMessage::Flush()
    @     0x7f29d27f41be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f29d2c6cf84  caffe::ReadProtoFromBinaryFile()
    @     0x7f29d2c8a9cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f29d2b8247a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f29d2b82501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7f29d1c26ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  9129 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting val set
E0516 02:11:50.690008  9278 extract_features.cpp:54] Using GPU
E0516 02:11:50.690439  9278 extract_features.cpp:60] Using Device_id=0
F0516 02:12:13.775943  9278 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7f2b838689fd  google::LogMessage::Fail()
    @     0x7f2b8386a89d  google::LogMessage::SendToLog()
    @     0x7f2b838685ec  google::LogMessage::Flush()
    @     0x7f2b8386b1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2b83ce3f84  caffe::ReadProtoFromBinaryFile()
    @     0x7f2b83d019cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f2b83bf947a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f2b83bf9501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7f2b82c9dec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  9278 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_probe set
E0516 02:12:16.299953  9420 extract_features.cpp:54] Using GPU
E0516 02:12:16.300331  9420 extract_features.cpp:60] Using Device_id=0
F0516 02:12:36.427316  9420 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7ffa727e39fd  google::LogMessage::Fail()
    @     0x7ffa727e589d  google::LogMessage::SendToLog()
    @     0x7ffa727e35ec  google::LogMessage::Flush()
    @     0x7ffa727e61be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ffa72c5ef84  caffe::ReadProtoFromBinaryFile()
    @     0x7ffa72c7c9cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7ffa72b7447a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7ffa72b74501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7ffa71c18ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  9420 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_gallery set
E0516 02:12:38.635035  9580 extract_features.cpp:54] Using GPU
E0516 02:12:38.635535  9580 extract_features.cpp:60] Using Device_id=0
F0516 02:12:57.957043  9580 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/jstl/jstl_iter_55000.caffemodel
*** Check failure stack trace: ***
    @     0x7f706e5339fd  google::LogMessage::Fail()
    @     0x7f706e53589d  google::LogMessage::SendToLog()
    @     0x7f706e5335ec  google::LogMessage::Flush()
    @     0x7f706e5361be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f706e9aef84  caffe::ReadProtoFromBinaryFile()
    @     0x7f706e9cc9cc  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f706e8c447a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f706e8c4501  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x408879  feature_extraction_pipeline<>()
    @     0x7f706d968ec5  (unknown)
    @           0x403e3e  (unknown)
scripts/routines.sh: line 93:  9580 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
prid
Traceback (most recent call last):
  File "eval/metric_learning.py", line 104, in <module>
    main(args)
  File "eval/metric_learning.py", line 85, in main
    M = _learn_metric(X, Y, args.method)
  File "eval/metric_learning.py", line 43, in _learn_metric
    M = np.eye(X.shape[1])
IndexError: tuple index out of range

viper
Traceback (most recent call last):
  File "eval/metric_learning.py", line 104, in <module>
    main(args)
  File "eval/metric_learning.py", line 85, in main
    M = _learn_metric(X, Y, args.method)
  File "eval/metric_learning.py", line 43, in _learn_metric
    M = np.eye(X.shape[1])
IndexError: tuple index out of range

3dpes
Traceback (most recent call last):
  File "eval/metric_learning.py", line 104, in <module>
    main(args)
  File "eval/metric_learning.py", line 85, in main
    M = _learn_metric(X, Y, args.method)
  File "eval/metric_learning.py", line 43, in _learn_metric
    M = np.eye(X.shape[1])
IndexError: tuple index out of range

cogito2012@k-SYS-7048GR-TR:~/dgd_person_reid-master$ 
////////////////////////////////////////////////////////////////

I wonder whether this problem results from small GPU memory (Actually 12G is enough), or caused by any other reason?

**Comment by Cysu** [comment]
It seems that the caffe is compiled without using MPI. Could you please check if [these lines](https://github.com/Cysu/caffe/blob/0eb706983bb42298f596303499dce1e09bf3d52d/Makefile.config.example#L8-L10) are uncommented and properly set in your `Makefile.config`?

**Comment by Cogito2012** [comment]
@Cysu Thanks for your help! And I have another question, my cudnn version is cudnn v3.0, and I don't   want to change it to cudnn v4.0 because it's another application's  requirement. Will this affect the installation of dgd_person_reid?

**Comment by Cysu** [comment]
Actually, you don't need to uninstall cudnn v3. You can just add the path to cudnn v4 (include and lib64) [here](https://github.com/Cysu/caffe/blob/0eb706983bb42298f596303499dce1e09bf3d52d/Makefile.config.example#L77-L78) and compile the caffe normally. Then add `export LD_LIBRARY_PATH=/path/to/cudnn/v4/lib64:$LD_LIBRARY_PATH` to `~/.bashrc` and restart the terminal.
