### ISSUE TITLE
The code of network architecture is not compatible with paper?

### ISSUE THREAD

**Issue by wangg12** [Cysu/dgd_person_reid#10]
Hi @Cysu, I just read about your excellent DGD paper and found a problem which made me confused. 

In Table 1 of the DGD paper[https://arxiv.org/pdf/1604.07528.pdf](https://arxiv.org/pdf/1604.07528.pdf), the strides of `conv1` to `conv3` are 2. 
I am confused why the output sizes are retained. 
So I checked your prototxt of the models and find that the conv kernels are `3x3 with stride 1 and pad 1`. Is this a **typo** in your paper?

**Comment by Cysu** [comment]
Oh. You're right. There's a typo in the paper. The first three convs are of stride 1. Thanks very much for pointing it out.

**Comment by wangg12** [comment]
Thanks @Cysu .
