### ISSUE TITLE
error in format-rawdata

### ISSUE THREAD

**Issue by huashuimu** [Cysu/dgd_person_reid#11]
when I run the format-rawdata.py,it comes wrong with the information
Traceback (most recent call last):
  File "data/format_cuhk03.py", line 5, in <module>
    from utils import *
ImportError: No module named utils
I have already add export PYTHONPATH=".:$PYTHONPATH" to ~/.bashrc,but it still comes wrong.

**Comment by Cysu** [comment]
It's a little bit weird. Did you restart the terminal after that?

**Comment by Cysu** [comment]
@huashuimu Have you resolved the problem?

**Comment by huashuimu** [comment]
@Cysu After I add the path and restart the terminal,it still comes wrong.So I have to add the tow files into the ./data and then it works.

**Comment by Cysu** [comment]
@huashuimu Thanks very much for the feedback. I will check if there are better ways to import local modules. Will close this issue for now and please feel free to reopen it if there are further problems.
