### ISSUE TITLE
about format_rawdata.sh

### ISSUE THREAD

**Issue by JaHangirYin** [Cysu/dgd_person_reid#12]
When I run the "scripts/format_rawdata.sh", it gives some errors

error:  invalid compressed data to inflateexternal/raw/cuhk03_release/cuhk-03.mat

**Comment by JaHangirYin** [comment]
Unable to read MAT-file

**Comment by Cysu** [comment]
Could you please manually unzip the `cuhk03_release.zip` to `external/raw/`, comment [this](https://github.com/Cysu/dgd_person_reid/blob/master/scripts/format_rawdata.sh#L9) line out, and run `scripts/format_rawdata.sh` again?

**Comment by JaHangirYin** [comment]
sorry,I forget to compile external/caffe . But when I run  _make j8 && make py__ , there are some new errors:  _./build_release/erc/caffe/proto/caffe.pb.h:20917:21:error:'kEmptyString' is not a member of 'google::protobuf::internal'_    
Thank you!

**Comment by Cysu** [comment]
It seems that the protobuf version is not compatible. Could you please `protoc --version` to see if the output is `libprotoc 2.x.x`? If not, maybe you can refer to the official [issue](https://github.com/BVLC/caffe/issues/19) that discusses how to configure the protobuf properly.

**Comment by JaHangirYin** [comment]
_libprotoc 2.5.0_ 
_opencv 3.0.0_

**Comment by Cysu** [comment]
That's a little bit weird. Does it link to other shared libraries? What's the output of `ldd $(which protoc)`?

**Comment by JaHangirYin** [comment]
I have solved these errors,but the error of running  _scripts/format_rawdata.sh_  is still existed; I found I cann't manually unzip the cuhk03_release.zip to external/raw/; I will download the zip file again . Maybe some new errors will appear.

**Comment by JaHangirYin** [comment]
_cuhk03_release.zip_ cann't manually unzip, it is so sad

**Comment by Cysu** [comment]
Did you download the dataset following the link in README? Could you please check if the md5sum equals to 728939e58ad9f0ff53e521857dd8fb43?

**Comment by Cysu** [comment]
@JaHangirYin Have you resolved the problem?

**Comment by JaHangirYin** [comment]
Yes, thank you!!Maybe there are some errors when I upload the datasets to the server. And I modified  _makefile.config_ , pass the compilation.

**Comment by Cysu** [comment]
That's great! Will close this issue for now. Please feel free to reopen it if there are further problems.
