### ISSUE TITLE
GPU數目疑問，結果與源碼不一致

### ISSUE THREAD

**Issue by gakkitw** [Cysu/dgd_person_reid#16]
你好，我想請問用兩張GPU並行訓練的用意是可以增強訓練還是只是為了增加訓練速度？
因為我用單張GPU(GTX Titan X)且沒動任何參數，跑出的結果cuhk03 top-1 高於paper的數值，我覺得不太合理，想請問你有什麼看法，謝謝！

**Comment by Cysu** [comment]
并行训练主要是为了加快速度，prototxt不改的话单卡多卡是等价的。
结果高于paper这个是有可能的，一是因为近期修复了一个iter_size的bug；二是因为不同的test split结果会略有差异，需要多做几次取平均。

**Comment by gakkitw** [comment]
感謝你的回答，我也多做了幾次取平均，取得了一些不錯的成果。但我還想再請教你一個問題，如果我想加入其他的datasets是否可行?如果可行我該從哪邊下手?期待你的答覆，麻煩你了。

**Comment by Cysu** [comment]
加入其他datasets的話可以：

1. 利用目前訓練好的model作爲起始，直接在新的datasets上進行finetune。
2. 把新的datasets加入到joint training的過程中。以market1501爲例，首先需要寫一個`data/format_market1501.py`將原始數據轉換成統一的格式；然後修改對應的prototxt和bash scripts，比如總人數變了，最後fc層的`num_output`也要跟着變。

**Comment by gakkitw** [comment]
不好意思再一次打擾你 我試著寫一個format_market1501.py將數據轉換成統一的格式並且修改對應的prototxt和bash scripts，但執行scripts/exp_individually.sh market1501後出現以下問題。想請問您該如何解決，感謝!
I0107 17:50:51.155105  6928 solver.cpp:410] Snapshotting to binary proto file external/exp/snapshots/individually/market1501_iter_10000.caffemodel
I0107 17:50:51.294667  6928 solver.cpp:705] Snapshotting solver state to binary proto fileexternal/exp/snapshots/individually/market1501_iter_10000.solverstate
I0107 17:50:51.469944  6928 solver.cpp:296] Iteration 10000, loss = 0.197288
I0107 17:50:51.469985  6928 solver.cpp:316] Iteration 10000, Testing net (#0)
I0107 17:51:03.065388  6928 solver.cpp:373] 	Test net output #0: accuracy = 0.947232
I0107 17:51:03.065440  6928 solver.cpp:373] 	Test net output #1: loss = 0.223257 (* 1 = 0.223257 loss)
I0107 17:51:03.065460  6928 solver.cpp:301] Optimization Done.
I0107 17:51:03.065465  6928 caffe.cpp:191] Optimization Done.
Extracting train set
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/libopencv_highgui.so.2.4)
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/liblzma.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libunwind.so.8)
E0107 17:51:03.548113 41037 extract_features.cpp:54] Using GPU
E0107 17:51:03.548696 41037 extract_features.cpp:60] Using Device_id=0
F0107 17:51:14.898651 41037 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File n.caffemodelxternal/exp/snapshots/individually/market1501_iter_10000
*** Check failure stack trace: ***
	@ 	0x7fad1a5f0daa  (unknown)
	@ 	0x7fad1a5f0ce4  (unknown)
	@ 	0x7fad1a5f06e6  (unknown)
	@ 	0x7fad1a5f3687  (unknown)
	@ 	0x7fad1aa9ec74  caffe::ReadProtoFromBinaryFile()
	@ 	0x7fad1aa9752c  caffe::ReadNetParamsFromBinaryFileOrDie()
	@ 	0x7fad1aab7cca  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
	@ 	0x7fad1aab7d51  caffe::Net<>::CopyTrainedLayersFrom()
	@       	0x409689  feature_extraction_pipeline<>()
	@ 	0x7fad19a20f45  (unknown)
	@       	0x404c4e  (unknown)
	@          	(nil)  (unknown)
scripts/routines.sh: line 93: 41037 Aborted             	(core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting val set
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/libopencv_highgui.so.2.4)
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/liblzma.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libunwind.so.8)
E0107 17:51:17.610769 41060 extract_features.cpp:54] Using GPU
E0107 17:51:17.611475 41060 extract_features.cpp:60] Using Device_id=0
F0107 17:51:28.920909 41060 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File n.caffemodelxternal/exp/snapshots/individually/market1501_iter_10000
*** Check failure stack trace: ***
	@ 	0x7f17ca312daa  (unknown)
	@ 	0x7f17ca312ce4  (unknown)
	@ 	0x7f17ca3126e6  (unknown)
	@ 	0x7f17ca315687  (unknown)
	@ 	0x7f17ca7c0c74  caffe::ReadProtoFromBinaryFile()
	@ 	0x7f17ca7b952c  caffe::ReadNetParamsFromBinaryFileOrDie()
	@ 	0x7f17ca7d9cca  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
	@ 	0x7f17ca7d9d51  caffe::Net<>::CopyTrainedLayersFrom()
	@       	0x409689  feature_extraction_pipeline<>()
	@ 	0x7f17c9742f45  (unknown)
	@       	0x404c4e  (unknown)
	@          	(nil)  (unknown)
scripts/routines.sh: line 93: 41060 Aborted             	(core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_probe set
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/libopencv_highgui.so.2.4)
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/liblzma.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libunwind.so.8)
E0107 17:51:31.729104 41081 extract_features.cpp:54] Using GPU
E0107 17:51:31.729830 41081 extract_features.cpp:60] Using Device_id=0
F0107 17:51:32.214601 41081 data_transformer.cpp:552] Check failed: datum_channels > 0 (0 vs. 0)
*** Check failure stack trace: ***
	@ 	0x7f617ccd3daa  (unknown)
	@ 	0x7f617ccd3ce4  (unknown)
	@ 	0x7f617ccd36e6  (unknown)
	@ 	0x7f617ccd6687  (unknown)
	@ 	0x7f617d067b41  caffe::DataTransformer<>::InferBlobShape()
	@ 	0x7f617d11b190  caffe::DataLayer<>::DataLayerSetUp()
	@ 	0x7f617d0fa70b  caffe::BaseDataLayer<>::LayerSetUp()
	@ 	0x7f617d0fa7e9  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
	@ 	0x7f617d19b9f9  caffe::Net<>::Init()
	@ 	0x7f617d19e95c  caffe::Net<>::Net()
	@       	0x40960a  feature_extraction_pipeline<>()
	@ 	0x7f617c103f45  (unknown)
	@       	0x404c4e  (unknown)
	@          	(nil)  (unknown)
scripts/routines.sh: line 93: 41081 Aborted             	(core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_gallery set
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/libtiff.so.5: no version information available (required by /usr/local/lib/libopencv_highgui.so.2.4)
external/caffe/build/tools/extract_features: /home/islab/anaconda2/lib/liblzma.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libunwind.so.8)
E0107 17:51:34.852541 41099 extract_features.cpp:54] Using GPU
E0107 17:51:34.853124 41099 extract_features.cpp:60] Using Device_id=0
F0107 17:51:35.364547 41099 data_transformer.cpp:552] Check failed: datum_channels > 0 (0 vs. 0)
*** Check failure stack trace: ***
	@ 	0x7f57a5ba6daa  (unknown)
	@ 	0x7f57a5ba6ce4  (unknown)
	@ 	0x7f57a5ba66e6  (unknown)
	@ 	0x7f57a5ba9687  (unknown)
	@ 	0x7f57a5f3ab41  caffe::DataTransformer<>::InferBlobShape()
	@ 	0x7f57a5fee190  caffe::DataLayer<>::DataLayerSetUp()
	@ 	0x7f57a5fcd70b  caffe::BaseDataLayer<>::LayerSetUp()
	@ 	0x7f57a5fcd7e9  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
	@ 	0x7f57a606e9f9  caffe::Net<>::Init()
	@ 	0x7f57a607195c  caffe::Net<>::Net()
	@       	0x40960a  feature_extraction_pipeline<>()
	@ 	0x7f57a4fd6f45  (unknown)
	@       	0x404c4e  (unknown)
	@          	(nil)  (unknown)
scripts/routines.sh: line 93: 41099 Aborted             	(core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Traceback (most recent call last):
  File "eval/metric_learning.py", line 110, in <module>
	main(args)
  File "eval/metric_learning.py", line 85, in main
	M = _learn_metric(X, Y, args.method)
  File "eval/metric_learning.py", line 43, in _learn_metric
	M = np.eye(X.shape[1])
IndexError: tuple index out of range
