### ISSUE TITLE
format-rawdata出错

### ISSUE THREAD

**Issue by duanLH** [Cysu/dgd_person_reid#2]
format-rawdata.sh时，运行format_数据集.py 的时候，提示很多函数未定义，并且script文件夹下的init.py文件为空。是不是少上传错了呢，还是我哪里弄错了

**Comment by Cysu** [comment]
您好，能提供一些错误信息吗？`data/__init__.py`是python用来初始化一个module用的，我们这里里面就是空的

**Comment by duanLH** [comment]
@Cysu  比如在format cuhh03数据集的时候，提示说没有定义mkdir_if_missing ,write_json 等等

**Comment by duanLH** [comment]
@Cysu  另一个问题，我只有一个GPU,然后不用openmpi 可以吗，makefile.config里把mpi 的内容都注释掉可以吗

**Comment by Cysu** [comment]
可否麻烦您试一下`export PYTHONPATH=.:$PYTHONPATH`，然后再运行`scripts/format_rawdata.sh`?

**Comment by duanLH** [comment]
@Cysu 麻烦您能说的详细一点吗。。我直接复制运行 export PYTHONPATH=.:$PYTHONPATH后在运行.sh文件，提示说
File "data/format_cuhk03.py", line 93, in <module>
    main(args)
  File "data/format_cuhk03.py", line 19, in main
    matdata = _load(args.cuhk03_dir)
  File "data/format_cuhk03.py", line 14, in _load
    matdata = loadmat(osp.join(cuhk03_dir, 'cuhk-03.mat'))
NameError: global name 'osp' is not defined

**Comment by duanLH** [comment]
@Cysu 谢谢你，，，好像可以了，，，太谢谢你的细心指导了。。。

**Comment by duanLH** [comment]
@Cysu  在运行make_db时又出问题了 
duan@duan:~/dgd_person_reid$ ./scripts/make_dbs.sh
Making cuhk03
Traceback (most recent call last):
  File "tools/make_lists_id_training.py", line 84, in <module>
    main(args)
  File "tools/make_lists_id_training.py", line 23, in main
    meta = read_json(osp.join(args.dataset_dir, 'meta.json'))
NameError: global name 'read_json' is not defined
Making train set
external/caffe/build/tools/convert_imageset: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by Cysu** [comment]
`NameError: global name 'read_json' is not defined` 这个可能还是PYTHONPATH的问题，可以把`export PYTHONPATH=.:$PYTHONPATH`添加到`~/.bashrc`后重新启动terminal。

`error while loading shared libraries: libboost_system.so.1.58.0` 这个可能是boost没链接上。您boost是怎么安装的呢？是通过系统的包管理（apt-get, yum, pacman ...）还是自己编译了一个呢？如果是自己编译了的话，要在`~/.bashrc`里面添加

    export LD_LIBRARY_PATH=/path/to/boost/lib:$LD_LIBRARY_PATH

这里`/path/to/boost/lib/`下面要包含`libboost_system.so.1.58.0`。

**Comment by duanLH** [comment]
@Cysu  又解决了，，大神，你太厉害了，，请收下膝盖～，，大神，能否给个联系方式☺～

**Comment by duanLH** [comment]
@Cysu  最后一个数据集还需要发邮件，就没用，，合并处理数据集的前两步把最后一个数据集注释了，然后合并数据集的时候出错了，，看来必须用最后一个吗，，，能否把最后一个数据集的下载链接给一下～，万分感谢

**Comment by Cysu** [comment]
感谢您的建议，但我没有权利redistribute最后这个数据集，暂时可能得发邮件给原作者才可以。我之后改一下代码把这个作为可选的吧，但实验需要重做，要花一些时间。

您可以通过邮件联系我 `st.cysu at gmail dot com`，谢谢。
