### ISSUE TITLE
關於加入新的dataset

### ISSUE THREAD

**Issue by gakkitw** [Cysu/dgd_person_reid#21]
你好，不好意思再一次打擾你，我是問題#16的提問者，我試著寫一個format_market1501.py將數據轉換成統一的格式並且修改對應的prototxt和bash scripts，但執行scripts/exp_individually.sh market1501後出現以下問題。想請問您該如何解決，感謝!
E0110 18:31:07.437958 27153 extract_features.cpp:54] Using GPU
E0110 18:31:07.453989 27153 extract_features.cpp:60] Using Device_id=0
F0110 18:31:18.749990 27153 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not fou.caffemodell/exp/snapshots/individually/market1501_iter_5000
*** Check failure stack trace: ***
    @     0x7effb9480daa  (unknown)
    @     0x7effb9480ce4  (unknown)
    @     0x7effb94806e6  (unknown)
    @     0x7effb9483687  (unknown)
    @     0x7effb992ec84  caffe::ReadProtoFromBinaryFile()
    @     0x7effb992753c  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7effb9947cda  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7effb9947d61  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x409689  feature_extraction_pipeline<>()
    @     0x7effb88b0f45  (unknown)
    @           0x404c4e  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 93: 27153 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting val set
E0110 18:31:21.511122 27173 extract_features.cpp:54] Using GPU
E0110 18:31:21.553755 27173 extract_features.cpp:60] Using Device_id=0
F0110 18:31:32.846850 27173 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not fou.caffemodell/exp/snapshots/individually/market1501_iter_5000
*** Check failure stack trace: ***
    @     0x7fef4be5adaa  (unknown)
    @     0x7fef4be5ace4  (unknown)
    @     0x7fef4be5a6e6  (unknown)
    @     0x7fef4be5d687  (unknown)
    @     0x7fef4c308c84  caffe::ReadProtoFromBinaryFile()
    @     0x7fef4c30153c  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fef4c321cda  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fef4c321d61  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x409689  feature_extraction_pipeline<>()
    @     0x7fef4b28af45  (unknown)
    @           0x404c4e  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 93: 27173 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_probe set
E0110 18:31:35.480466 27194 extract_features.cpp:54] Using GPU
E0110 18:31:35.487788 27194 extract_features.cpp:60] Using Device_id=0
F0110 18:31:35.970708 27194 data_transformer.cpp:552] Check failed: datum_channels > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f8c24682daa  (unknown)
    @     0x7f8c24682ce4  (unknown)
    @     0x7f8c246826e6  (unknown)
    @     0x7f8c24685687  (unknown)
    @     0x7f8c24a16b51  caffe::DataTransformer<>::InferBlobShape()
    @     0x7f8c24aca1a0  caffe::DataLayer<>::DataLayerSetUp()
    @     0x7f8c24aa971b  caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7f8c24aa97f9  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f8c24b4aa09  caffe::Net<>::Init()
    @     0x7f8c24b4d96c  caffe::Net<>::Net()
    @           0x40960a  feature_extraction_pipeline<>()
    @     0x7f8c23ab2f45  (unknown)
    @           0x404c4e  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 93: 27194 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_gallery set
E0110 18:31:38.982168 27212 extract_features.cpp:54] Using GPU
E0110 18:31:38.999352 27212 extract_features.cpp:60] Using Device_id=0
F0110 18:31:39.510656 27212 data_transformer.cpp:552] Check failed: datum_channels > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f3e7a8ecdaa  (unknown)
    @     0x7f3e7a8ecce4  (unknown)
    @     0x7f3e7a8ec6e6  (unknown)
    @     0x7f3e7a8ef687  (unknown)
    @     0x7f3e7ac80b51  caffe::DataTransformer<>::InferBlobShape()
    @     0x7f3e7ad341a0  caffe::DataLayer<>::DataLayerSetUp()
    @     0x7f3e7ad1371b  caffe::BaseDataLayer<>::LayerSetUp()
    @     0x7f3e7ad137f9  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f3e7adb4a09  caffe::Net<>::Init()
    @     0x7f3e7adb796c  caffe::Net<>::Net()
    @           0x40960a  feature_extraction_pipeline<>()
    @     0x7f3e79d1cf45  (unknown)
    @           0x404c4e  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 93: 27212 Aborted                 (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Traceback (most recent call last):
  File "eval/metric_learning.py", line 110, in <module>
    main(args)
  File "eval/metric_learning.py", line 85, in main
    M = _learn_metric(X, Y, args.method)
  File "eval/metric_learning.py", line 43, in _learn_metric
    M = np.eye(X.shape[1])
IndexError: tuple index out of range

**Comment by Cysu** [comment]
It seems that the commands in the scripts are not correct. Could you please change these [two lines](https://github.com/Cysu/dgd_person_reid/blob/master/scripts/exp_individually.sh#L19-L20) to

```shell
echo "train_model ${exp} ${dataset}"
echo "test_model ${exp} ${dataset} $(get_trained_model ${exp} ${dataset})"
```

and run the script again?

**Comment by gakkitw** [comment]
Thank you for your reply, but still can not work after changing these two lines.
I will continue to find out where the problem is and hope you can provide me with other ideas if you know.

**Comment by Cysu** [comment]
This two lines are just for debug. Could you please show the output of these two lines?

**Comment by gakkitw** [comment]
train_model individually market1501
test_model individually market1501 external/exp/snapshots/individually/market150.caffemodel
Sorry, I am a novice. Thank you for your help.

**Comment by gakkitw** [comment]
So these two lines are right?

**Comment by Cysu** [comment]
Does the training start or not? If not, could you please run it manually with
```shell
external/caffe/build/tools/caffe train -solver models/individually/market1501_solver.prototxt -gpu 0
```
and see what's the error message?

**Comment by gakkitw** [comment]
Will begin training, but test will appear above error.
And I tried to follow what you said, but it say:
No command 'caffe' found, did you mean:
 Command 'caff' from package 'signing-party' (universe)
caffe: command not found

**Comment by gakkitw** [comment]
你好，我已經成功執行exp_individually.sh market1501，但在exp_jstl.sh出現了問題，想請教您對應到jstl的prototxt中num_output: 2629是怎麼決定的

**Comment by Cysu** [comment]
When you merge all the datasets together, it will print out this number [here](https://github.com/Cysu/dgd_person_reid/blob/master/tools/merge_lists_single_task.py#L27).

**Comment by gakkitw** [comment]
不好意思再次打擾你，請問如果我想將自己的dataset加入進去並且只做test，那我的dataset也需要進行`make_dbs.sh`嗎?  如果只做test我該從何下手，還麻煩你給我建議，謝謝。

**Comment by Cysu** [comment]
One possible way is to
1. Create `test_gallery.txt` and `test_probe.txt` that contains lines of `image_filename person_id` for your dataset. Put them under `external/exp/db/new_dataset/`.
2. Convert images to LMDBs with
```bash
source scripts/make_dbs.sh
make_db /path/to/your/images/ external/exp/db/new_dataset
```
3. Do evaluation
```bash
source scripts/routines.sh
test_model exp_new_dataset new_dataset /path/to/pretrained/model_iter_xxx.caffemodel
```

**Comment by gakkitw** [comment]
Thank you for all your assistance. I really appreciate your help in resolving the problem.
