### ISSUE TITLE
Caffe build error with openmpi

### ISSUE THREAD

**Issue by kimjm0309** [Cysu/dgd_person_reid#22]
Hi, I'm trying to build caffe with openmpi flags on, getting error messages as follows.
How can I resolve this?

.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/tools/caffe.o: In function `test()':
caffe.cpp:(.text+0xaf6): undefined reference to `caffe::Net<float>::SyncOutput()'
caffe.cpp:(.text+0xb33): undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
caffe.cpp:(.text+0xb40): undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/tools/caffe.o: In function `boost::detail::sp_counted_impl_p<caffe::MPIJobQueue<float> >::dispose()':
caffe.cpp:(.text._ZN5boost6detail17sp_counted_impl_pIN5caffe11MPIJobQueueIfEEE7disposeEv[_ZN5boost6detail17sp_counted_impl_pIN5caffe11MPIJobQueueIfEEE7disposeEv]+0xe): undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/tools/caffe.o: In function `caffe::MPIJobQueue<float>::Get()':
caffe.cpp:(.text._ZN5caffe11MPIJobQueueIfE3GetEv[_ZN5caffe11MPIJobQueueIfE3GetEv]+0x9): undefined reference to `caffe::MPIJobQueue<float>::singleton_'
caffe.cpp:(.text._ZN5caffe11MPIJobQueueIfE3GetEv[_ZN5caffe11MPIJobQueueIfE3GetEv]+0x31): undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
caffe.cpp:(.text._ZN5caffe11MPIJobQueueIfE3GetEv[_ZN5caffe11MPIJobQueueIfE3GetEv]+0xa0): undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::Push(caffe::MPIJobQueue<double>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::~MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncDiff()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<double>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::WaitAll()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncData()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::Net<float>::SyncOutput()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::Push(caffe::MPIJobQueue<float>::Job const&)'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::singleton_'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<double>::MPIJobQueue()'
.build_release/lib/libcaffe.so: undefined reference to `caffe::MPIJobQueue<float>::~MPIJobQueue()'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
make: *** Waiting for unfinished jobs....
make: *** [.build_release/tools/convert_labelset.bin] Error 1
make: *** [.build_release/tools/extract_features.bin] Error 1
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1
make: *** [.build_release/tools/convert_bboxset.bin] Error 1
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
make: *** [.build_release/tools/caffe.bin] Error 1
make: *** [.build_release/tools/convert_imageset.bin] Error 1

**Comment by Cysu** [comment]
It's a little bit weird as the errors occur in the linking stage, which means that `include/caffe/net.hpp` contains these methods and the `USE_MPI` macro is defined, while `src/caffe/net.cpp` does not.

Could you please first make sure `src/caffe/net.cpp` also contains certain methods like [SyncData](https://github.com/Cysu/caffe/blob/b7472b5d64b90baa69339648cc154e3bd2a42596/src/caffe/net.cpp#L1053-L1055), and then `make clean && make -j8` again?
