### ISSUE TITLE
About add new dataset

### ISSUE THREAD

**Issue by montego7878** [Cysu/dgd_person_reid#23]
I add new dataset, but it has a error
----------------------------------------------------------------------------------------------------------------------------------
montego7878@montego7878-All-Series:~$ ./下載/dgd_person_reid/scripts/exp_individually.sh Test
I0217 17:26:38.334089 12962 caffe.cpp:170] Use GPU with device ID 0
I0217 17:26:38.502809 12962 caffe.cpp:178] Starting Optimization
I0217 17:26:38.502868 12962 solver.cpp:41] Initializing solver from parameters: 
test_iter: 3
test_interval: 20
base_lr: 0.1
display: 20
max_iter: 2700
lr_policy: "stepdecr"
gamma: 0.04
momentum: 0.9
weight_decay: 0.0005
stepsize: 100
snapshot_prefix: "external/exp/snapshots/individually/Test"
solver_mode: GPU
net: "models/individually/Test_trainval.prototxt"
test_initialization: true
average_loss: 20
iter_size: 2
min_lr: 0.0005
I0217 17:26:38.502887 12962 solver.cpp:79] Creating training net from net file: models/individually/Test_trainval.prototxt
F0217 17:26:38.502918 12962 io.cpp:34] Check failed: fd != -1 (-1 vs. -1) File not found: models/individually/Test_trainval.prototxt
*** Check failure stack trace: ***
    @     0x7fa22b389daa  (unknown)
    @     0x7fa22b389ce4  (unknown)
    @     0x7fa22b3896e6  (unknown)
    @     0x7fa22b38c687  (unknown)
    @     0x7fa22ba6a6ed  caffe::ReadProtoFromTextFile()
    @     0x7fa22ba7f934  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7fa22ba8b922  caffe::Solver<>::InitTrainNet()
    @     0x7fa22ba8c7de  caffe::Solver<>::Init()
    @     0x7fa22ba8c976  caffe::Solver<>::Solver()
    @           0x40e4e3  caffe::GetSolver<>()
    @           0x407080  train()
    @           0x4053b6  main
    @     0x7fa22a89bf45  (unknown)
    @           0x4059b1  (unknown)
    @              (nil)  (unknown)
Extracting train set
E0217 17:26:38.640938 12986 extract_features.cpp:54] Using GPU
E0217 17:26:38.641165 12986 extract_features.cpp:60] Using Device_id=0
F0217 17:26:43.106864 12986 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/individually/Test_iter_2700.caffemodel
*** Check failure stack trace: ***
    @     0x7f1726fdedaa  (unknown)
    @     0x7f1726fdece4  (unknown)
    @     0x7f1726fde6e6  (unknown)
    @     0x7f1726fe1687  (unknown)
    @     0x7f17274618a3  caffe::ReadProtoFromBinaryFile()
    @     0x7f17274769b4  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f172742e0b7  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f172742e126  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x4080b8  feature_extraction_pipeline<>()
    @     0x7f172640ef45  (unknown)
    @           0x403bce  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 96: 12986 已經終止            (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting val set
E0217 17:26:44.411387 13007 extract_features.cpp:54] Using GPU
E0217 17:26:44.411638 13007 extract_features.cpp:60] Using Device_id=0
F0217 17:26:48.852941 13007 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/individually/Test_iter_2700.caffemodel
*** Check failure stack trace: ***
    @     0x7f2f07ea4daa  (unknown)
    @     0x7f2f07ea4ce4  (unknown)
    @     0x7f2f07ea46e6  (unknown)
    @     0x7f2f07ea7687  (unknown)
    @     0x7f2f083278a3  caffe::ReadProtoFromBinaryFile()
    @     0x7f2f0833c9b4  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f2f082f40b7  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f2f082f4126  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x4080b8  feature_extraction_pipeline<>()
    @     0x7f2f072d4f45  (unknown)
    @           0x403bce  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 96: 13007 已經終止            (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_probe set
E0217 17:26:50.129348 13028 extract_features.cpp:54] Using GPU
E0217 17:26:50.129575 13028 extract_features.cpp:60] Using Device_id=0
F0217 17:26:54.599745 13028 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/individually/Test_iter_2700.caffemodel
*** Check failure stack trace: ***
    @     0x7fd5e7a20daa  (unknown)
    @     0x7fd5e7a20ce4  (unknown)
    @     0x7fd5e7a206e6  (unknown)
    @     0x7fd5e7a23687  (unknown)
    @     0x7fd5e7ea38a3  caffe::ReadProtoFromBinaryFile()
    @     0x7fd5e7eb89b4  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fd5e7e700b7  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fd5e7e70126  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x4080b8  feature_extraction_pipeline<>()
    @     0x7fd5e6e50f45  (unknown)
    @           0x403bce  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 96: 13028 已經終止            (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Extracting test_gallery set
E0217 17:26:55.872711 13048 extract_features.cpp:54] Using GPU
E0217 17:26:55.872951 13048 extract_features.cpp:60] Using Device_id=0
F0217 17:27:00.327179 13048 io.cpp:52] Check failed: fd != -1 (-1 vs. -1) File not found: external/exp/snapshots/individually/Test_iter_2700.caffemodel
*** Check failure stack trace: ***
    @     0x7fcb9c08ddaa  (unknown)
    @     0x7fcb9c08dce4  (unknown)
    @     0x7fcb9c08d6e6  (unknown)
    @     0x7fcb9c090687  (unknown)
    @     0x7fcb9c5108a3  caffe::ReadProtoFromBinaryFile()
    @     0x7fcb9c5259b4  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fcb9c4dd0b7  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fcb9c4dd126  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x4080b8  feature_extraction_pipeline<>()
    @     0x7fcb9b4bdf45  (unknown)
    @           0x403bce  (unknown)
    @              (nil)  (unknown)
scripts/routines.sh: line 96: 13048 已經終止            (core dumped) ${CAFFE_DIR}/build/tools/extract_features ${trained_model} ${model} ${blob},label ${result_dir}/${subset}_features_lmdb,${result_dir}/${subset}_labels_lmdb ${num_iters} lmdb GPU 0
Traceback (most recent call last):
  File "eval/metric_learning.py", line 158, in <module>
    main(args)
  File "eval/metric_learning.py", line 139, in main
    M = _learn_metric(X, Y, args.method)
  File "eval/metric_learning.py", line 95, in _learn_metric
    M = np.eye(X.shape[1])
IndexError: tuple index out of range

**Comment by Cysu** [comment]
It says `models/individually/Test_trainval.prototxt` is missing. You may need to copy a net config there and 
- change the data source
- change the last fully-connected layer's `name` and `num_output` to the number of ids in your dataset.

**Comment by montego7878** [comment]
@Cysu  Thanks so much
