### ISSUE TITLE
詢問routines.sh內，train, val, test_probe, test_gallery意義與資料來源

### ISSUE THREAD

**Issue by tony36486** [Cysu/dgd_person_reid#24]
最近在學習DGD，從results\individually的輸出去追發現輸出在routines.sh內的extract_features()定義。
其中train, val, test_probe, test_gallery的意義與資料來源，無法理解。
原本猜測是在format_資料庫.py中定義的trainval, test_probe, test_gallery，但數目上對不起來。

**Comment by Cysu** [comment]
These subsets are defined in format_(dataset name).py as you said. Could you please elaborate on where the number mismatches?

When extracting features, we will compute [how many iterations](https://github.com/Cysu/dgd_person_reid/blob/master/scripts/routines.sh#L97) do we need, which equals to `ceil(#samples / 100)`. It could extract slightly more sample features to LMDBs, but we will always [truncate to](https://github.com/Cysu/dgd_person_reid/blob/master/scripts/routines.sh#L107) the exact number of samples later when converting to numpy.

**Comment by tony36486** [comment]
從extract_features()去理解train, val, test_probe, test_gallery是四個參數。
但在 format_(dataset name).py內僅找到trainval, test_probe, test_gallery三個參數被定義。
想知道trainval如何轉換成train和val。

**Comment by Cysu** [comment]
When running `scripts/make_dbs.sh`, it will call `tools/make_lists_id_training.py`, where we will split the trainval into train and val. Please check the code [here](https://github.com/Cysu/dgd_person_reid/blob/master/tools/make_lists_id_training.py#L26).

**Comment by tony36486** [comment]
thanks for your kindness help.
