### ISSUE TITLE
Hi,can convert_lmdb_to_numpy.py  num*27*37*96 lmdb into matlab?

### ISSUE THREAD

**Issue by wuhuo714** [Cysu/dgd_person_reid#27]
Nums is the total number of pictures.What I find is that convert_lmdb_to_numpy.py only works for  N*D arrary data.

**Comment by Cysu** [comment]
You can convert to N*D numpy.ndarray first and then reshape it.

**Comment by wuhuo714** [comment]
OK，thanks！！
