### ISSUE TITLE
could you please provide the file `external/exp/db/cuhk01/train.txt`?

### ISSUE THREAD

**Issue by Lmy0217** [Cysu/dgd_person_reid#28]
Hi, I'm trying to test and verify results on cuhk01 dateset with the given pre-trained model and euclidean distance. I need produce trainset and testset. But we know that the given pre-trained model is trained on cuhk01, so I don't know how to divide cuhk01. If you provided the file which save trained images' indexes, my problem would be solved. So, could you please provide the file `external/exp/db/cuhk01/train.txt`?

**Comment by Cysu** [comment]
Please find the split files that used for the pretrained model and archived logs at https://drive.google.com/open?id=0B67_d0rLRTQYbjNDV0VfZ2lseHM.

**Comment by Lmy0217** [comment]
Thank you very much.
