### ISSUE TITLE
Can I only using one GPU 

### ISSUE THREAD

**Issue by duanLH** [Cysu/dgd_person_reid#3]
I only have one GPU ， so I do not want to use openmpi ,if without openmpi ,can I using this project sucessfully ?

**Comment by Cysu** [comment]
Sure. You can safely comment out the lines of `USE_MPI`, `MPI_INCLUDE`, and `MPI_LIB` in `Makefile.config`. But also remember to change [these lines](https://github.com/Cysu/dgd_person_reid/blob/master/scripts/routines.sh#L70-L74) to

    GLOG_logtostderr=1 ${CAFFE_DIR}/build/tools/caffe train \
      -solver ${solver} -gpu 0 2>&1 | tee ${log}

and 

    GLOG_logtostderr=1 ${CAFFE_DIR}/build/tools/caffe train \
      -solver ${solver} -weights ${pretrained_model} -gpu 0 2>&1 | tee ${log}
