### ISSUE TITLE
My Python implementation performs much worse than the paper

### ISSUE THREAD

**Issue by GBJim** [Cysu/dgd_person_reid#33]
Hi all

I wrote a [Python implementation](https://github.com/GBJim/demo/blob/master/dgd_extraction.ipynb) covering the feature extraction and on VIPeR dataset.
(The CMC function is imported from the [CMC.py](https://github.com/Cysu/dgd_person_reid/blob/master/utils/cmc.py) of this repo)

Using the **pretrained JSTL+DGD mode**  provided by @Cysu,  I only got **19.33%** of Top 1 accuracy.  It's far from the 37.7% on the paper. 

I guess there are bugs in my script, but I couldn't find it.

**Comment by Cysu** [comment]
I'm not sure, but one possible reason is that we first resize the image to 160x64, then get center-crop of 144x56, instead of directly resizing it to 144x56.

**Comment by GBJim** [comment]
Hi @Cysu 
I forgot to transform RGB input into BGR format.
The Top 1 accuracy reached 37.3% after adding  `transformer.set_channel_swap('data', (2,1,0))`

I will also try to the central cropping strategy you used.  
Thank you!

**Comment by Cysu** [comment]
@GBJim Good to hear that! I didn't notice this point either.
