### ISSUE TITLE
where is the guideddropout layer??

### ISSUE THREAD

**Issue by BrettLL** [Cysu/dgd_person_reid#34]
hi, One question is that where is the guideddropout layer??
and shouldn't it in caffe folder?

**Comment by Cysu** [comment]
It is in the caffe folder actually, at [here](https://github.com/Cysu/caffe/blob/ab985827d63de737c5e05cbddb53c3a8484cd20f/src/caffe/layers/guided_dropout_layer.cpp).

**Comment by BrettLL** [comment]
@Cysu sorry, I missed it~
