### ISSUE TITLE
测试效果达不到 源码的水平

### ISSUE THREAD

**Issue by song1998** [Cysu/dgd_person_reid#4]
您好，因为我用的980显卡，显存不够大，因此把 train 的batchsize 改为15，test 15.跑完之后，单独的cuhk03 50000次accuary0.98,测试之后top1仅为63.5%。因此咨询一下，是不是batchsize改小了这个原因导致，训练还没到最优。另外您的显卡是什么型号，多大显存。

**Comment by Cysu** [comment]
我用的是两个6G的Titan Black并行训练的，并且iter_size设成2，所以合起来每个minibatch相当于有100个sample，如果太小的话确实会影响最终的结果。

单卡980ti的话您可以试试把训练batch_size设成25，val设成10，同时在solver里面把iter_size设成4，这样应该能放得下。
