### ISSUE TITLE
how to extract domain from the video

### ISSUE THREAD

**Issue by walk2out** [Cysu/dgd_person_reid#5]
can we input the surveillance video directly? or we can only input the processed image?

**Comment by Cysu** [comment]
Currently we only support image data. One possible way to use video data is to convert them into image frames (with proper labels).

**Comment by walk2out** [comment]
Thank you! And is it effective to connect your application to the pedestrian detection application?

**Comment by Cysu** [comment]
Yes. It would be straightforward to first do the pedestrian detection on video frames, and then use our method to do re-identification.

You may also refer to our new work ["End-to-End Deep Learning for Person Search"](https://arxiv.org/abs/1604.01850) and the [code is also available](https://github.com/ShuangLI59/person_search).

**Comment by walk2out** [comment]
oh, it's very useful, thank you very much!
